name: GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install, build, and upload your site
      uses: withastro/action@v6
      with:
          path: .
          node-version: 24
          # Use a reasonable recent pnpm version
          package-manager: pnpm@10.8.1
          build-cmd: pnpm run build

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
